version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/package
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 100
      runas: ec2-user
  AfterInstall:
    - location: cleanup.sh
      timout: 100
      runas: ec2-user
      