version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 100
      runas: ec2-user
  ApplicationStop:
    - location: stop.sh
      timeout: 100
      runas: ec2-user