version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 200
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 100
      runas: root